/**
 * src/lib/useFiles.ts
 *
 * Reads the pre-fetched ImageKit file list from src/data/files.json
 * (generated by scripts/fetch-imagekit-files.js) and groups it by folder,
 * mirroring the old DRIVE_FILES.<folder>.<file> shape so the rest of the
 * app reads naturally.
 *
 * No network call, no API key — this is plain static data bundled at
 * build time. Rerun the fetch script and rebuild whenever ImageKit
 * contents change.
 *
 * Usage:
 *   const { files, byFolder } = useFiles();
 *   folder(byFolder, 'Galeria po godzinach') -> ImageKitFile[]
 */

import filesData from '../data/files.json';

export type ImageKitFile = {
    fileId: string;
    name: string;
    filePath: string;
    folder: string;
    url: string;
    fileType: 'image' | 'non-image';
    extension: string;
    isPdf: boolean;
    width?: number;
    height?: number;
    size: number;
    createdAt: string;
};

type FilesData = {
    files: ImageKitFile[];
    generatedAt: string | null;
};

const data = filesData as FilesData;

function groupByFolder(files: ImageKitFile[]): Record<string, ImageKitFile[]> {
    const map: Record<string, ImageKitFile[]> = {};
    for (const f of files) {
        const key = f.folder || '(root)';
        if (!map[key]) map[key] = [];
        map[key].push(f);
    }
    return map;
}

const allFiles: ImageKitFile[] = data.files ?? [];
const groupedFiles = groupByFolder(allFiles);

/**
 * Hook-shaped accessor, kept as a function for a familiar call style
 * (`useFiles()`), even though there's no actual fetching/loading state
 * since the data is bundled at build time.
 */
export function useFiles() {
    return {
        files: allFiles,
        byFolder: groupedFiles,
        loading: false as const,
        error: null as null,
        generatedAt: data.generatedAt,
    };
}

/** Find a single file by (partial, case-insensitive) name match within a folder. */
export function findByName(
    files: ImageKitFile[],
    nameFragment: string
): ImageKitFile | undefined {
    const needle = nameFragment.toLowerCase();
    return files.find((f) => f.name.toLowerCase().includes(needle));
}

/**
 * Look up a folder's files by a fuzzy match on folder name, so small
 * naming differences between this code and the real ImageKit folder
 * names don't break the build.
 *
 * Example: folder(byFolder, "Hiszpania 2025-2026 Galeria") matches an
 * ImageKit folder literally named
 * "Hiszpania 2025-2026 Galeria po godzinach".
 */
export function folder(
    byFolder: Record<string, ImageKitFile[]>,
    nameFragment: string
): ImageKitFile[] {
    const normalize = (s: string) => s.toLowerCase().replace(/[\s\-–—_]+/g, ' ').trim();
    const needle = normalize(nameFragment);

    for (const [key, files] of Object.entries(byFolder)) {
        if (normalize(key).includes(needle)) return files;
    }
    return [];
}

/** Only image files (excludes PDFs and other non-image types). */
export function onlyImages(files: ImageKitFile[]): ImageKitFile[] {
    return files.filter((f) => f.fileType === 'image');
}

/** Only PDF files. */
export function onlyPdfs(files: ImageKitFile[]): ImageKitFile[] {
    return files.filter((f) => f.isPdf);
}